
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import NavBar from '@/components/NavBar'
import { ClerkProvider } from '@clerk/nextjs'
import { SiteFooter } from '@/components/site-footer'
import { ProModal } from '@/components/pro-modal'
import { Toaster } from '@/components/ui/toaster'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>

          <div className='bg-[#0f1014] flex flex-col min-h-screen mx-auto 2xl:max-w-screen-xl'>
            <ProModal />

            <NavBar />

            {children}



            <SiteFooter />

            <Toaster />

          </div>







        </body>
      </html>
    </ClerkProvider>
  )
}
